### ISSUE TITLE
Créer en plus un autre .tsv pour insertion directe dans GES1Point5

### ISSUE THREAD

**Issue by JulieAndre27** [JulieAndre27/Moulinette_missions#20]
Le format de la sortie est intéressant et pratique, cependant on ne peut pas insérer directement ce doc dans le site GES1Point5.
Le site demande en effet un fichier .tsv ou .csv avec des noms de colonnes bien précis.
L'idéal serait donc de générer directement ce fichier, en plus de l'autre.
Il contient les colonnes suivantes (vides si besoin) :

"# mission"	Date de départ	Ville de départ	Pays de départ	Ville de destination	Pays de destination	Mode de déplacement	Nb de personnes dans la voiture	Aller Retour (OUI si identiques, NON si différents)	Motif du déplacement (optionnel)	Statut de l'agent (optionnel)

On a déjà toutes les infos, il s'agit juste de remettre les colonnes dans l'ordre.

[exemple_files.zip](https://github.com/JulieAndre27/Moulinette_missions/files/14229552/exemple_files.zip)

**Comment by hippalectryon-0** [comment]
#21
